[server]
fileWatcherType = "poll"
layout = "wide"
initial_sidebar_state = "expanded"

[theme]
primaryColor = "#6B46C1"
backgroundColor = "#F8F6FF"
secondaryBackgroundColor = "#EEEAF5"
textColor = "#1A202C"
font = "monospace"
